const express = require('express');
const router = express.Router();
const auth = require('../middlewares/authMiddleware');
const { requireAdmin } = require('../middlewares/roleMiddleware');
const controller = require('../controllers/receiptController');
router.use(auth);
router.post('/', requireAdmin, controller.createReceipt);
router.get('/', requireAdmin, controller.getReceipts);
router.get('/stats', requireAdmin, controller.getReceiptStats);
router.get('/mine', controller.getMyReceipts);
router.get('/:id', controller.getReceiptById);
module.exports = router;
