-- AlterTable
ALTER TABLE `dossier` ADD COLUMN `inscriptionStatus` ENUM('EN_COURS', 'VALIDE') NOT NULL DEFAULT 'EN_COURS',
    ADD COLUMN `traductionStatus` ENUM('EN_COURS', 'VALIDE') NOT NULL DEFAULT 'EN_COURS',
    ADD COLUMN `visaStatus` ENUM('EN_COURS', 'VALIDE') NOT NULL DEFAULT 'EN_COURS';
